version: 2.1
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-8.1'
      VERSION: '3.0.0'
      VENDOR: 'asus'
      CODENAME: 'Z00A'
      FLAVOR: 'eng'
      TEST_BUILD: 'true'
      MAINTAINER: '@Imranpopz'
      EXTRA_CMD: "rm -rf external/busybox && git clone -b oreo-x86 https://scm.osdn.net/gitroot/android-x86/external-busybox.git external/busybox && cd build && wget https://github.com/SKYHAWK-Recovery-Project/shrp_build/commit/bcd4dd5be30764542959de864119c5ef2d66aaf8.patch && patch -p1 < bcd* && cd .. "
      CHANGELOG: |
        TEST BUILD
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
           
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
          
            
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: 'android-8.1'
