version: 2.1
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-8.1'
      USE_SECRET_BOOTABLE: 'true'
      SECRET_BR: 'redesign3'
      # PBRP_BRANCH: 'android-9.0'
      VERSION: '2.9.1'
      VENDOR: 'asus'
      CODENAME: 'Z00A'
      FLAVOR: 'userdebug'
      # BUILD_LUNCH: 'omni_h30u10-userdebug'
      TEST_BUILD: 'true'
      MAINTAINER: '@Imranpopz'
      CHANGELOG: |
        TEST BUILD
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
           
            wget -q https://raw.githubusercontent.com/imranpopz/vendor_utils/pb/build.sh
            source build.sh
          
            
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: 'android-8.1'
